Repository Team-Go-Local/go_local_microservice, pull requests merged in 2021-02, with the labels that each got.

#14 Search endpoint 2
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/fixtures/vcr_cassettes/place_search.yml
  spec/services/map_service_spec.rb
  spec/spec_helper.rb
Labels: Microservice, iteration 1

#17 Remove secure: key from file
  .travis.yml
Labels: bug

#18 Edit file format to match BE and FE
  .travis.yml
Labels: bug

#19 Response test
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/map_controller.rb
  app/poro/place.rb
  app/serializers/place_serializer.rb
  spec/poros/place_poro_spec.rb
  spec/requests/place_serializer_spec.rb
  spec/spec_helper.rb
Labels: Microservice
